#!/bin/bash

# Roda o linter. Se falhar, exibe o guia de uso da Warj-Group
npx commitlint --edit "$1" || {
  echo -e "\n\033[0;31m❌ ERRO: Mensagem de commit fora do padrão Warj-Group!\033[0m"
  echo "----------------------------------------------------------------"
  echo "PADRÃO: {tipo}/{id_yt}: Descrição"
  echo "EXEMPLO: feat/WARJ-1: Inicializado repositório"
  echo "----------------------------------------------------------------"
  exit 1
}